### ISSUE TITLE
Rendering and Saving each Frame's Data

### ISSUE THREAD

**Issue by Erfan-Ahmadi** [windows-toolkit/Lottie-Windows#147]
I discovered Lottie-Windows yesterday and the tutorial only works high-level and lets the XML file handle it.

I don't need to work with XML files nor show anything on the screen. 
I want to import the .json file and be able to process the image frame by frame.

How can I render Lottie and save the Current Frame in order to process it further?

**Comment by sohchatt** [comment]
This sounds like an interesting use-case. Can you tell us more about why you need to use JSONs to generate images for each frame? 

The Lottie-Windows implementation uses the Windows.UI.Composition APIs to render in a separate process, so the only way of analyzing each frame output would be to use [screen capture APIs](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture), which is a very round-about way of merely generating images from your JSON file. 

There are some simpler offline approaches I'm aware of:

- Use AfterEffects to export to media formats instead of exporting as Bodymovin JSON. This is the traditional way of using AfterEffects and makes most sense if you have access to the source AEP.
- If you only have an exported Bodymovin JSON, [lottiefiles.com](https://lottiefiles.com/) has a [download as .MP4 or GIF option](https://twitter.com/LottieFiles/status/1147164119532916736).

**Comment by Erfan-Ahmadi** [comment]
It's because I want something platform independent to draw it and get the pure image data so I can export or show it with any arbitrary resolution maybe even analyze it's data. So far rlottie by Samsung has been great but there is nothing better than consistently maintained official Lottie Renderer.

**Comment by sohchatt** [comment]
You could also try using Lottie-Web (https://github.com/airbnb/lottie-web), an officially maintained renderer that outputs an SVG tree, which you can both rasterize and inspect. It is maintained by Hernan, the creator of Bodymovin, so I expect that it'll be as correct as anything else out there. Unfortunately, this feature is not in our plans for Lottie-Windows at the time being.
