### ISSUE TITLE
Create AnimatedVisualPlayer progress double? Documentation for ProgressObject?

### ISSUE THREAD

**Issue by jjouppi** [windows-toolkit/Lottie-Windows#348]
Hello!

Looking to incorporate the animated visual player into a preexisting media player I'm working on. I have a custom seek bar slider that receives a double to update it's position as media plays. I can set the progress of the AnimatedVisualPlayer just fine with .SetProgress but is there a way to receive the progress of a currently playing LottieSource as a double?

I've been referencing the Lottie Viewer sample heavily but the method used to update the seek bar is incomparable with my current solution. Seems that there could be some solution within the .ProgressObject created by the animated visual player but hitting a wall when trying to understand how that works.

Is there a simple solution to my problem or any resources to better understand how to utilize the .ProgressObject?

Thanks in advance!

**Comment by simeoncran** [comment]
Hi @jjouppi. Lottie-Windows renders Lottie files in a separate process (dwm.exe). This is great for performance, but it means your app's process cannot know which frame of the Lottie is currently being rendered while the animation is playing.

So how does Lottie Viewer update its scrubber bar? It's a trick. When Lottie Viewer is playing, the scrubber's thumb is being drawn by dwm.exe without the app's involvement. The position of the thumb is tied to the progress of the animation using an [ExpressionAnimation](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.expressionanimation?view=winrt-19041).

Code for the Scrubber is here: https://github.com/windows-toolkit/Lottie-Windows/blob/master/LottieViewer/Scrubber.xaml.cs

The ProgressObject is a [CompositionObject](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositionobject?view=winrt-19041) that has a property set value named "Progress" that is updated by dwm.exe for every frame as the animation progresses. Unfortunately for your scenario, the value isn't visible to the app while it is being updated, only when the animation stops.

There is no simple solution to this. There is no way to get a callback on every frame. In order to get notified about every frame the Lottie would have to be rendered in the app's process. In-app rendering is very flexible, and is how all the other Lottie implementations work, however Lottie-Windows was written to take advantage of dwm.exe because it gives the highest possible performance at the expense of some flexibility.
