### ISSUE TITLE
Access Height and Width of LottieSource? Documentation for LottieVisualDiagnostics?

### ISSUE THREAD

**Issue by jjouppi** [windows-toolkit/Lottie-Windows#349]
Having difficulty retrieving the Height and Width of .json file set as the source of an AnimatedVisualPlayer. From the documentation, it seems that there is that there is a LottieVisualDiagnostics object created when the .json file is set as the source of the AnimatedVisualPlayer? However, I'm having trouble understanding how to access this information.

Referencing the Lottie Viewer application, I'm unable to parse how the information is retrieved to so that it can be displayed in the lower left corner. Are there any resources or documentation that may help me understand exactly what's going on? Thanks in advance for any help you can provide.

**Comment by simeoncran** [comment]
Hi @jjouppi.  Have a look at https://github.com/windows-toolkit/Lottie-Windows/blob/master/source/Lottie/LottieVisualDiagnostics.cs. That object is made available on the AnimatedVisualPlayer.Diagnostics property. You just need to cast the Diagnostics value to LottieVisualDiagnostics and you'll be able to use it.

Be aware that LottieVisualDiagnostics is designed for diagnostics purposes and its interface could change in future versions. There is no general way to get Lottie metadata from the AnimatedVisualPlayer because AnimatedVisualPlayer has no knowledge about Lottie concepts.
