### ISSUE TITLE
I'm not able to use external image assets in Lottie Windows

### ISSUE THREAD

**Issue by mandrigin** [windows-toolkit/Lottie-Windows#351]
I found [this line of code](https://github.com/windows-toolkit/Lottie-Windows/blob/8608ab2fd55e995498be98b536965107bbc6524d/source/LottieToWinComp/Images.cs#L48) that should parse external assets, but I never got any Uri with `file://localhost/` to work properly. Each guide suggest using `msapx:///Assets/<path>` for that.

```csharp
surface = LoadedImageSurface.StartLoadFromUri(new Uri($"file://localhost/{externalImageAsset.Path}{externalImageAsset.FileName}"));
```

Where should I put images for my Lottie animation so it actually loads them?`externalImageAsset.Path` in my case is `images/`

PS: The same animation works great with embedded images.

**Comment by simeoncran** [comment]
Hi Igor, are you using LottieVisualSource or Lottiegen when you are having this issue?

**Comment by mandrigin** [comment]
Hi @simeoncran! I use LottieVisualSource.

**Comment by simeoncran** [comment]
LottieVisualSource currently doesn't support images. You need LottieGen to use images.
The missing piece here is being able to have LottieVisualSource ask your code to load the image. We don't trust LottieVisualSource to load images from arbitrary places because it is a security risk, and it might not have access anyway. See #167

**Comment by mandrigin** [comment]
Hmm. Okay. 

Just out of curiosity, how does loading images from urls in json more of a security risk than loading that json itself from an arbitrary URI?

Also, what this loading from `file://localhost` is about. I can double check if that is called for JSON files but that looks weird.

I know that Android and iOS allow file loading and Android forces you to pick an image directory and iOS and Mac strips paths and just requires images to be in assets.

So if Lottie for Windows would emulate Mac it would just use file names and tries to load `msapx:///Assets/<file_name>` which has to be bundled if I understand the concept correctly. Would that be a solution?

**Comment by simeoncran** [comment]
The file://localhost is a placeholder put there during translation but LottieGen expands to the ms-appx:///Assets location. We currently don't do that for LottieVisualSource because if you know your assets at build time you might as well use LottieGen. I'm interested to know whether that's not a reasonable assumption for your case.

I was thinking that we'd add the ability to register a delegate with LottieVisualSource that would be called when an image is required. That way you are in complete control of how the loading happens for arbitrary Lottie files. It would then be simple to choose how you implemented the loading. That would be more flexible than the Android or iOS systems. This should be straightforward to add to LottieVisualSource, it just hasn't been done yet.

**Comment by mandrigin** [comment]
Thanks for the info!
