### ISSUE TITLE
Animations not rendering correctly

### ISSUE THREAD

**Issue by juwens** [windows-toolkit/Lottie-Windows#422]
Minimal example: https://github.com/juwens/AppUwpLottie

The sample contains 4 Lottie animations.

# Animation one: (the default LottieLogo1) renders fine

# Animation two (a countdown from 10 to 0): numbers are missing 

https://lottiefiles.com/15116-count-down-10

|actual|expected|
|--|--|
|![image](https://user-images.githubusercontent.com/11560817/107630405-c3f35b80-6c63-11eb-8f2b-a9ac6decf32a.png)|![image](https://user-images.githubusercontent.com/11560817/107630341-a6be8d00-6c63-11eb-8a90-ef42099e230c.png)|

# Animation three (a countdown  from 3 to 1): numbers are missing 

Source: https://lottiefiles.com/11250-count-down

|actual|expected|
|--|--|
|![image](https://user-images.githubusercontent.com/11560817/107630486-e2595700-6c63-11eb-8dc6-dc1a89fc4753.png)|![image](https://user-images.githubusercontent.com/11560817/107630622-116fc880-6c64-11eb-8f75-3538b5a8d723.png)|

# Animation four (a countdown from 3 to 1 to GO): 
Source: https://lottiefiles.com/8384-count-down-animation

- only displays the initial rectangle
- numbers are missing
- animation/transition of rectangle-color is missing
- final GO is missing

## actual
![image](https://user-images.githubusercontent.com/11560817/107630894-7c210400-6c64-11eb-82cb-a7de44a3e590.png)

## expected
![image](https://user-images.githubusercontent.com/11560817/107631096-c4d8bd00-6c64-11eb-93d6-490272352978.png) ![image](https://user-images.githubusercontent.com/11560817/107631124-cf935200-6c64-11eb-883b-314025c3ca2a.png) ![image](https://user-images.githubusercontent.com/11560817/107631140-d4f09c80-6c64-11eb-8565-bebc1f3ace26.png) ![image](https://user-images.githubusercontent.com/11560817/107631164-dae67d80-6c64-11eb-9300-a4553e4a589e.png) ![image](https://user-images.githubusercontent.com/11560817/107631183-e0dc5e80-6c64-11eb-9dbd-8fad362ee28f.png) ![image](https://user-images.githubusercontent.com/11560817/107631021-ad013900-6c64-11eb-830f-3ebdced17aa9.png)

**Comment by simeoncran** [comment]
Hi @juwens,

1. https://lottiefiles.com/15116-count-down-10 requires that you set a non-white background, otherwise you can't see the numbers. The numbers are white on a transparent background.
2.  https://lottiefiles.com/11250-count-down and https://lottiefiles.com/8384-count-down-animation will not work with Lottie-Windows because of the use of Text layers. If you have access to After Effects and the original AEP file, you can re-export the files with BodyMovin and have it generate paths for the text.

LottieGen outputs error messages for 11250 and 8384 which indicate the problem.

warning LT0019: Text layer is not supported.
warning LT0034: Mask requires a UAP version of at least 8. Affects only UAP version 7.
warning LT0034: Path animation requires a UAP version of at least 11. Affects UAP versions from 8 up to and including 10.

and

warning LT0019: Text layer is not supported.
warning LT0021: 3D layer is not supported.
warning LT0034: Mask requires a UAP version of at least 8. Affects only UAP version 7.

Closing this issue because the lack of support for Text and 3D are limitations we're aware of (and are extremely hard for us to fix using the current architecture).
