### ISSUE TITLE
Request: offer same features on viewer as on the Android app

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [windows-toolkit/Lottie-Windows#91]
Meaning as this one:
https://github.com/airbnb/lottie-android
https://play.google.com/store/apps/details?id=com.airbnb.lottie

**Comment by sohchatt** [comment]
@AndroidDeveloperLB which particular features do you think are missing from [Lottie Viewer](https://aka.ms/lottieviewer)? 

Some added context:
- Our philosophy has been to keep the Lottie Viewer app relatively simple for now, focused primarily on the design-to-code workflow. As such, we want it to be friendly to non-technical users as well. We're happy to add features based on what's useful for our users, so please let us know.
- The [code samples](https://github.com/windows-toolkit/Lottie-Windows/tree/master/samples) are shipped as a separate standalone app called [Lottie Samples](https://aka.ms/lottiesamples).

**Comment by AndroidDeveloperLB** [comment]
Please try it. It has many that are missing on Windows viewer.
Here are some features that I think you should add:
1. Showing various Lottie files from the Lottie-Files website, including search feature.
2. Showing frame count, current frame.
3. Showing render-graph
4. Showing warnings
5. Showing the border of the animation. 
6. Trim animation, though for some reason it doesn't have the ability to atually export it.
7. Full screen
8. "scale" - Zoom in/out. Could be nice to do it by using mouse wheel too.
9. Show keyframes.
10. Disable/enable repeating.
11. scanning of QR code, but since it's a PC, it could be nice to have a different feature: Open those files by default, and if it's not a Lottie file (because sadly it's json files which can be opened in other ways), offer to use an alternative app.
12. Avoid the splash screen animation. Even the app doesn't have this. Why would a PC take so much time to load the app?

Attached video to show most of those features.
[device-2019-03-25-220156.zip](https://github.com/windows-toolkit/Lottie-Windows/files/3005223/device-2019-03-25-220156.zip)

**Comment by sohchatt** [comment]
Thanks for the video; the Android app is certainly feature-rich and powerful. We hope to grow Lottie Viewer over time with more features that are useful to designers and developers. To that effect, please  do file separate issues as needed, based on our conversation below.

> 1. Showing various Lottie files from the Lottie-Files website, including search feature.

You can open individual URIs using the file picker UI, but it might be useful to have better integration with lottiefiles.com in the future. Please create a new feature request and we can prioritize based on how interesting this ask is for other users.

> 2. Showing frame count, current frame.

The slider in Lottie Viewer shows you the current Progress if you interact with it (pointer press and scrub). We assume that Progress would be more useful than FrameCount since it is the only concept that is exposed via the AnimatedVisualPlayer's API (for example: PlayAsync() has fromProgress and toProgress, SetProgress(), etc.). Do you still want frame count and current frame information? If so, why?

In case you're using frame information to measure frame-rate, the rendering is actually managed by the Windows Compositor, providing 60 fps consistently. 

> 3. Showing render-graph

It is worth noting that all of the information on Android may be interpreted as the performance cost of the animation to your application's process, whereas, for Lottie-Windows, all rendering is performed in an external process and as such has no actionable consequences for the application author in most Lottie cases. The Windows.UI.Composition APIs (which Lottie-Windows is built upon) provide retained-mode rendering for the entire application, so isolating vector graphic data with fine granularity may be an interesting challenge. That being said, I do believe that there is value in providing actionable feedback when certain rendering operations resulting from a Lottie file are likely to degrade performance. Please do file a separate issue requesting richer performance insights.  

> 4. Showing warnings

The Lottie Viewer already has an Issues icon in the top right that lights up if there are any known issues with the JSON file. The Issues then provide you with actionable information by redirecting to docs hosted on this repo. Those docs are a work in progress currently and will be updated within the next few days  #30 

> 5. Showing the border of the animation.

The Lottie Viewer's canvas (upon which the Lottie animation plays) is sized to match the animation's dimensions. In addition, the dimensions from AfterEffects are specified in the bottom left. As such, a border may not be needed since what you're seeing is all of the animation and nothing else.

> 6. Trim animation, though for some reason it doesn't have the ability to atually export it.

This is an interesting feature request -- consider filing as a separate issue.

> 7. Full screen

How and why do you plan on using full screen? How does it differ from maximizing the size of the app window?

> 8. "scale" - Zoom in/out. Could be nice to do it by using mouse wheel too.

This is an interesting feature request -- consider filing as a separate issue.

> 9. Show keyframes.

How do you plan on using this feature? Especially, how do you understand which layers and layer contents correspond to visuals on screen?

> 10. Disable/enable repeating.

Currently we enable repeating by default since certain types of animations (icons, etc.) are very short, lasting only a few milliseconds. More thoughts are in #53 -- consider re-opening the issue if you feel strongly about this.

> 11. scanning of QR code, but since it's a PC, it could be nice to have a different feature: Open those files by default, and if it's not a Lottie file (because sadly it's json files which can be opened in other ways), offer to use an alternative app.

Let's discuss this request in more detail on the issue you filed #90 .

> 12. Avoid the splash screen animation. Even the app doesn't have this. Why would a PC take so much time to load the app?

The splash screen was a deliberate attempt to demonstrate the usage of Lottie animations in innovative ways, not to mask app loading time. It's certainly not required, but we assumed might be a playful thing to keep around, and as a reference for those trying to build their own. However, I'm open to the idea of removing it if others feel like it's gratuitous and unnecessary.

> 13. Since it's installed via the Play Store, it will get auto updates. I hope this one also gets updated...

Certainly should! As a matter of fact, I just put out a new update yesterday with support for Bodymovin v5.5.0. Do let us know if you didn't get an update.

**Comment by AndroidDeveloperLB** [comment]
1. I don't think there are enough people visiting this repository every day and looking on various requests... Here:
https://github.com/windows-toolkit/Lottie-Windows/issues/93
2. Why not show the number in a static way? It's a static count after all. Stays the same no matter what... The current frame should also be shown, both as you play, and when you stop or drag the slider.
3. It is useful when we want to focus on performance, and when we want to use the Lottie file on mobile. Here:
https://github.com/windows-toolkit/Lottie-Windows/issues/94
4. Good. Can you please show an example file that will trigger warnings?
5. I disagree. You can't say that it resizes. What if I show it in full screen? It won't resize. I want to know the boundaries of the animation, to see if it has padding or not, to see the empty parts, to see if it can be minimized or should have more empty space. This is important in most cases that the animation needs to be placed together with other things around it, to align nicely, and yet not overlap. Please do consider adding it. I use it a lot on the viewer for Android, to see why the animation didn't show well and pushed other things too much.
6. ok:
https://github.com/windows-toolkit/Lottie-Windows/issues/95
7. Just more space to show the content. Maybe double clicking on the animation (like on video players, including even YouTube) it will toggle full screen.
8. ok : 
https://github.com/windows-toolkit/Lottie-Windows/issues/96
9. That's used on the app. Try it. It explains to you which are used and when.
10. ok
11. Very different feature request. There I request a plugin for Explorer that will show a thumbnail for the files. Here I ask for file association (when you double click a Lottie file). Sadly, since Lottie files are just json files (including extension), it should first detect if indeed the content is of Lottie animation, and then open in an external app (such as Notepad++) of our choice (set via the settings), instead of trying to view the animation. I also suggest that since it's a json file, there would be an option to open on a third party app, to view as textual content.
12. Well you could just have it as the default animation that gets opened at first, allowing the user to see the viewer in action right away, with all its features for it.
13. I don't see a way to check the current version. Not in the app, not in the "uninstall a program" screen (which the app doesn't exist in it, actually), and not on the "Microsoft Store". I think I now know why people mock Microsoft for its store... Could you perhaps add "about" screen, to show the current version? Maybe you could even show it upon starting the app, or in the title of the window, or when right clicking on the title of the window (many choices for you where to put it)?

**Comment by sohchatt** [comment]
> I don't see a way to check the current version

You can check the app version in Settings > Apps and Features > Lottie Viewer > Advanced Options > Version. Or simply search for "Lottie Viewer" in Start > App Settings , which should take you to the relevant UI. The About page you propose is certainly a better solution (the Viewer, as mentioned earlier, is very bare bones for the initial version) -- please feel free to open a new feature request for an About page.

Thanks for the detailed feedback and opening all the other individual issues. Closing this one for now.

**Comment by AndroidDeveloperLB** [comment]
@sohchatt Please put the version in a more visible place, inside the app itself.

**Comment by AndroidDeveloperLB** [comment]
Here, a request for the about window:
https://github.com/windows-toolkit/Lottie-Windows/issues/99
