### ISSUE TITLE
Request: show render-graph while playing 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [windows-toolkit/Lottie-Windows#94]
to show how well the animation plays, and how it affects performance.

**Comment by simeoncran** [comment]
@AndroidDeveloperLB  - it's not clear to me what we should show. I'm going to close this for now because it hasn't gotten any traction for so long, but feel free to reactivate it with more information. It would help if you could include a link to the Android app that you're referring to, your expectations about the information you expect to see (screenshots welcome!).

For Windows, the best tools are probably Windows Performance Analyzer, but note that Lotties run their animations and rendering in dwm.exe, not in your app, so you'd want to look at the performance of dwm.exe.

**Comment by AndroidDeveloperLB** [comment]
@simeoncran I'm talking about Lottie app:
https://play.google.com/store/apps/details?id=com.airbnb.lottie

And there is also a screenshot of it:
https://lh3.googleusercontent.com/fs5VxDfTwesPyVMrkqp_gTmJrv6C8VMSWFy6MPsuXGIoZeocwJlVs6gLpy7rvgCzPdU=w1536-h736-rw

**Comment by AndroidDeveloperLB** [comment]
If you wish, I can show you a video too.

**Comment by simeoncran** [comment]
I see it now.

I don't think detailed info about rendering is possible on Windows. The Android way of rendering is very different from Lottie-Windows. Lottie-Windows tells the Windows compositor (DWM.exe) what to render and it all gets rendered there along with all the other content on your screen. And Lottie-Windows tries very hard to optimize what it tells the compositor to do. This allows it to be a lot more efficient but it means we can no longer associate a piece of GPU work with a layer.

As I mentioned above, the Windows Performance Analyzer will tell you how DWM is performing, so that is probably your best bet.

If that doesn't work well for you, let me know a bit more about your scenario and I'll try to help.

**Comment by AndroidDeveloperLB** [comment]
Can you put something alternative perhaps? Maybe count of Vector elements being rendered at any given time, in a graph? This could be a different estimate to show how complex the Lottie file is, to help decide if it's ok to be used on Android.

**Comment by simeoncran** [comment]
Because the Lottie Viewer tool is about making sure that Lotties rendered with Lottie-Windows look ok, and because Windows renders Lotties in a very different way from Android this would require Lottie-Viewer to be redesigned to figure out how Android would render each frame.

That's outside the scope of what Lottie Viewer is ever likely to do.

Your best bet for accurate results would be to test on Android.

If you wanted a tool that could take a Lottie file on a Windows machine, read it, and report something about what's in it, the LottieGen tool would be a good starting point, but you'd have to figure out how to relate what's in the file to what Android will do with it.

**Comment by AndroidDeveloperLB** [comment]
@simeoncran 
But Lottie files are used in more platforms than Windows, and I wanted to use it while developing for Android .
Some might want to develop it for the web too, which is also supported on mobile devices.

I wanted a tool on windows to view Lottie files, and make it easier to check them out before using them, to make a good decision if it's ok or not.

**Comment by simeoncran** [comment]
@AndroidDeveloperLB, OK, I understand why this would be useful. I've added this to the Lottie Viewer feature backlog, but to ensure your expectations are set I'll reiterate that this seems to be outside of the scope of Lottie Viewer because Lottie Viewer is (currently) a tool to support Lottie-Windows only.

Maybe that will change or someone will offer to do the work.

**Comment by AndroidDeveloperLB** [comment]
@simeoncran Well, technically I can run an emulator of Windows - on an Android device :)
Or, I can run Windows on a very low end machine...
Why does it matter on which platform? Performance is always something to look forward to improve.
And Lottie files aren't some image files. Those are used by developers, so they are supposed to be used in various places, and they are advertised as cross platform.

**Comment by simeoncran** [comment]
Right, but the Lottie-Windows project has so far been entirely about enabling Lottie on Windows. The other platforms already had support so we have focused on Windows support.

The platform matters because each platform renders Lottie files in different ways, with Windows being the most unusual. The Lottie-Windows code is all about taking a Lottie file and translating it into commands for the DWM to go and figure out how to render. The commands given to DWM are very different from the frame-by-frame rendering done by Android.

That's not to say the Lottie Viewer couldn't take the parsed Lottie file and run some algorithm over it that would give some indication of how it would render on Android, but that algorithm doesn't currently exists, and I don't know how it would be written.

Note that running on a low end Windows machine may not tell you anything about how it will run on Android, again because the way Lottie-Windows renders is so different from Android.

Maybe I'm not understanding what your workflow is exactly. I'm most familiar with the workflow of a designer making an animation which they hand to a developer to integrate and they iterate until the look and performance is acceptable. It sounds like you are doing something different - you are finding Lottie files from around the web and wanting to quickly figure out if you can use them in an Android project without having access to the designer - is that right?

**Comment by AndroidDeveloperLB** [comment]
Compare the number of Android developers that develop the apps inside Android, to those that develop inside Windows OS, or any desktop OS...

This tool can easily be useful for Android developers. Many tools for Android developers exist on Windows OS. Many are also cross platform, at least for desktop.

The platform doesn't matter if the tool can help with suggesting if a Lottie file seems too complex or not. Android Studio does it for VectorDrawable and it doesn't need to run an emulator of Android to suggest to do something about it. Granted, it's not an animation and just an SVG replacement, but it can still give developers some clue about how "heavy" it is, even if you don't render it (not sure if it's a static analysis or a dynamic one).

As for the purpose of the feature, it doesn't matter who made the file. It matters if the file is considered light enough. 

Suppose for example a designer made an SVG file. Some SVG files can be incredibly complex and heavy, even for Windows OS. If the developer finds out about it, he can tell the designer that it's too heavy and that he should either optimize it or consider an alternative (a non-vector image file).

Same thing can be for Lottie files.

**Comment by simeoncran** [comment]
I agree that what you're suggesting can be useful for Android developers. But given that there is no design for how this would work in Lottie Viewer, and considering the goals of the project, I don't know how else I can help right now apart from leaving it in the backlog in case someone wants to provide that functionality.

If you know enough about how Android renders that you can specify what the static analysis should do then that would move things in the right direction. Is that something you could do?

**Comment by AndroidDeveloperLB** [comment]
Sorry, I'm not an expert on how Lottie is implemented on Android. 
Frankly other than incompatibility in some cases (I think when it uses an image) I almost never saw an issue with using Lottie in terms of performance. 
That being said, I always used very simple Lottie animations... 

So, sorry about this. I just thought it could be a nice addition.
Is it possible to at least put FPS counter? Could that be an easy-to-implement feature ? Later you could make a graph out of it (for each point in the animation).

**Comment by simeoncran** [comment]
For FPS, because the rendering is being done by the Windows compositor (DWM) the FPS would be telling you something about the performance of the system compositing and rendering of all the screen contents, not just the Lottie part. And if it's getting to 60FPS then all you can surmise is that it managed to render each frame in < 16.666mS. There's no way to isolate the performance to just the Lottie file. If you have only one screen, you could maximize the Lottie Viewer so that very little else needs to be rendered, and then you could look at the frame times for DWM.

Even that isn't a great solution though, as you'd then have to correlate the frames produced by Lottie Viewer with the frames produced by DWM.

And even if you could get that to work, the results would tell you only about whether any frames were dropped on the particular computer hardware you're on.

If you wanted to do that manually I can try and talk you through doing it on WPA but it will be a somewhat manual process, and it feels like a big waste of time because ultimately I think you just want to know whether the animation looks smooth in your app, not whether it hits 60 fps in Lottie Viewer.

We have played with some techniques of running multiple copies of a Lottie in order to see how many we can run at once, and then looking at CPU and GPU usage. If your goal was to determine the relative cost of a particular animation on a particular Windows machine then that works pretty well. We use that in order to fine tune animations to minimize their CPU and GPU costs for some scenarios. But for that you also need access to the designer (which is why I was asking about your workflow earlier), and a lot of knowledge about how a Lottie file translates to Windows code.

**Comment by AndroidDeveloperLB** [comment]
Well Android is about as fragmented as PC, in terms of both hardware and software.
Thus any measurement is still as valid as on Android, just as an indication and as a comparison to others.
It's like a benchmark. It doesn't tell you much, but it gives you a clue about how well it works.
If something goes x % worse, it might mean it will become this % worse on others.

Why do you talk only about 60FPS , though? Is this the max for Lottie?

**Comment by simeoncran** [comment]
60FPS is the most common frame rate of PC monitors. Lottie-Windows will attempt to animate at whatever is the frame rate of the primary monitor. It will not render at any other rate - it will drop frames if necessary in order to stay synchronized with the monitor.

There's a lot of cleverness in the Windows renderer that I doubt is in Android such that the performances of the 2 are unlikely to be comparable except at a very coarse level.

**Comment by AndroidDeveloperLB** [comment]
I see. OK. What about instead of FPS, complexity-per-second measurement?
I don't know how Lottie works, but if it was some 3d model, I could tell "number of polygons rendered on the screen, per second". 
The less that are rendered, the less work it is for the GPU/CPU to handle it.
So, instead of performance of the current hardware, show information about the work itself that the Lottie file presents.

**Comment by simeoncran** [comment]
That would be a huge job and it's only tangentially related to Lottie-Windows.
I can explain further why this is expensive to do if you like, but that won't solve the problem you're trying to solve, so I won't go into detail unless you ask.

A model like "polygons per second" is way too simplistic for Lottie because it doesn't take into account the large amount of optimization that Lottie-Windows does, nor the differences between the Android and Windows ways of rendering. Now maybe Android doesn't do any optimization so you could come up with a simpler analysis that was specific to Android, but supporting Android is not a goal of Lottie-Windows, so I'd only be likely to add it to Lottie-Windows if it was cheap to do. Reusing AirBnB code that is written for the Android APIs is not cheap because the 2 platforms are so different. Maybe you can talk the AirBnB folks into providing the functionality that can be integrated into Lottie-Windows. Even then there's no guarantee that it would be accepted.

**Comment by AndroidDeveloperLB** [comment]
@simeoncran 
Isn't it possible to calculate how long each frame took to render?
Is there any other way to have a clue of how intense an animation could be, or at least which parts of it?

**Comment by simeoncran** [comment]
I know how to measure how long each frame took if you are prepared to control the environment very carefully so as to prevent anything else from rendering at the same time, and then you collect a trace with [WPA](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/windows-performance-analyzer) and then analyze the trace. In other words, it's doable, but not very practical.

But even harder than that, you (I believe) want to then extrapolate those results back to Android. But Android renders very differently from Windows. If a Lottie file renders fast on Windows, it could still be terrible on Android.

**Comment by AndroidDeveloperLB** [comment]
I think something is better than nothing.

But there are other nice features that exist on the Android app that could be nice for the Windows app. Please try it out and see.
