### ISSUE TITLE
Request: offer to zoom in/out (scale)

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [windows-toolkit/Lottie-Windows#96]
Could be nice to do it by using mouse wheel too.
Also please show the scale number.

**Comment by simeoncran** [comment]
Is this just so you can see detail in an animation? Why not use After Effects for that? And what would the scale number mean - Lottie files contain vector graphics, so there's really no intrinsic size to begin with (apart from the intrinsic size of any referenced images). Closing for now because this has been sitting for so long with no traction, but feel free to reactivate with more info.

**Comment by AndroidDeveloperLB** [comment]
I'm talking about viewing the animation. Please check this app to see what I mean.

https://play.google.com/store/apps/details?id=com.airbnb.lottie

It's not about modifying the file at all.
