### ISSUE TITLE
[Dynamic Properties] Runtime color replacement in LottieVisualSource

### ISSUE THREAD

**Issue by hinterlandcreative** [windows-toolkit/Lottie-Windows#98]
The Android and iOS SDKs for Lottie have support for replacing colors in an animation. Would be nice to get the same functionality for the Windows SDK. One use case would be if you want to use the same animation in several different apps with distinct branding and colors.

Thanks!

**Comment by hinterlandsupplyco** [comment]
I know we could compile the annimations to C# and follow the example in the samples, but we are using json files in our app for several reasons that make using the compiled versions not feasible.

**Comment by sohchatt** [comment]
Thanks for the feedback, @hinterlandsupplyco . Adding a Dynamic Properties API is certainly on our backlog, and as you pointed, our current workaround of [modifying the codegen class](https://github.com/windows-toolkit/Lottie-Windows/blob/master/samples/LottieSamples/AnimatedVisuals/LottieLogo1_Modified.cs) has restrictions when working with JSON. 

We'd love to understand more about how you're using Lottie-Windows and the restrictions and requirements of your workflow: what are the reasons that make using codegen infeasible for you?

**Comment by hinterlandsupplyco** [comment]
@sohchatt  We are using `Lottie-Windows` in a Xamarin.Forms environment so we would like to share resources across implementations.

The two biggest issues we've run into are related to not being able to get a Frame Count from the `LottieVisualSource` so we can at least convert frame based information into progress based information and this issue, that we can't change layer colors or apply a mask/filter to change colors.

**Comment by sohchatt** [comment]
@hinterlandsupplyco we're investigating how to add support for dynamic properties to Lottie-Windows so you can edit the colors at run-time. Do you have a sample project (using Lottie-Xamarin, or otherwise) that you can share with us so we may better understand the specifics of your use-case?

**Comment by hinterlandsupplyco** [comment]
@sohchatt we would definitely want to bind to resources. We have two apps (with implementations on iOS, Android and Windows) which are in the same product family and we share resources between these projects. Each app uses a suite of colors. Ideally we want to generate one set of lottie files and use dynamic properties to bind to the app's primary color.

One of the animations we use all over our apps is a download progress indicator which is advanced by frame position (and then plays an animation at the end of the progress). This is a very simple animation, but we would the color of a specific layer to the app's primary color.

It would be wonderful to be able to use the dynamic properties api via XAML and code.

An example of this for `Lottie-Android` can be found here: 
```Java
LottieAnimationView animationView = findViewById(R.id.animation_view);
animationView.addValueCallback(
        new KeyPath("some-layer", "**"),
        LottieProperty.COLOR_FILTER,
        new SimpleLottieValueCallback<ColorFilter>() {
            @Override
            public ColorFilter getValue(LottieFrameInfo<ColorFilter> frameInfo) {
                return new PorterDuffColorFilter(Color.CYAN, PorterDuff.Mode.SRC_ATOP);
            }
        }
);
```

**Comment by sohchatt** [comment]
Do you use the lottie-android control directly instead of lottie-xamarin? It doesn't seem that lottie-xamarin  supports dynamic properties, so I'm curious to understand exactly how you're mixing platform-specific code with lottie-xamarin.

As far as I can tell, there is no unified API for dynamic properties across iOS and Android, so, at least for the dynamic properties case, you're going to have separate implementations for each platform. In that case, is the codegen approach for Windows still a deal breaker?

**Comment by hinterlandsupplyco** [comment]
@sohchatt For sure. Good questions. 

For the first of our two apps in this product family we have native implementations for each platform and therefore use that platforms' implementation of Lottie directly. 

For the second app, which is xamarin based, we have in the past only needed to display simple monochrome animations used during new user onboarding and have used `Lottie-Xamarin`.

The first app uses lottie animations extensively though as part of the UX design (within buttons and in place of icons, progress bars, etc.), but most of these uses are not being seen in the second app as the support for lottie within the xamarin ecosystem is not as robust (and because of the issues we've noticed in Lottie-UWP). But we want both apps to have feature/ux parity and that will likely mean our own Xamarin layer over the native implementations (or a PR to the `Lottie-Xamarin` project) to support dynamic properties. We will hold off on this work though until WinUI 3.0 and the work being discussed here with dynamic properties is in.

In our case, the codegen approach is likely still a deal breaker because we want to share assets. So in our xamarin based app it would be very cumbersome to have one platform using codegen'd animations and the other platforms using json within the same controls. It would be difficult to deal with 3 seperate implementations of dynamic properties, but not nearly as difficult as one platform using codegen'd animations and the rest using json files. Secondly, it makes it harder to update those assets as you have to update the animations if they are in two places (json and c#) and most designers would not be able to update a codegen'd animation without a developer getting involved.

**Comment by simeoncran** [comment]
This is partially solved with the 6.1 release, but only for codegen. The old way in the samples was pretty hard. The new way is really easy as long as you have someone who can modify the After Effects project to annotate the colors to indicate which ones should be dynamic.

I think the only missing piece is to add support to LottieVisualSource.

**Comment by simeoncran** [comment]
@traore-i - we need to figure out what sort of API should be added to LottieVisualSource to enable this, and the priority.

**Comment by nishitha-burman** [comment]
This is supported in codegen, currently no plans to add this to LottieVisualSource.

**Comment by under3415** [comment]
Is this done or abandoned? if former, do you have a code example?

**Comment by nishitha-burman** [comment]
Hi @under3415, currently this is supported in codegen but not LottieVisualSource. Do you need it supported in LottieVisualSource?

**Comment by under3415** [comment]
yeah, sort of. I have hundreds of little animations. If I make them into classes that would bloat my executable, I'd much rather have them in json as content.

> 
> 
> Hi @under3415, currently this is supported in codegen but not LottieVisualSource. Are you asking about support in LottieVisualSource?

yeah, sort of. I have hundreds of little animations. If I make them into classes that would bloat my executable, I'd much rather have them in json as content.

**Comment by steam3d** [comment]
Can you show After Effects project example? I can't understand how to specify color
