### ISSUE TITLE
Request: add "about" window, which will include the version of the app

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [windows-toolkit/Lottie-Windows#99]
As the title says.
Should also include the licenses for each library that was used.

**Comment by simeoncran** [comment]
This information is available (right click on "Lottie Viewer" on the start menu). It will show you the version. I'm not convinced that adding a menu to get to the version is going to add much to the experience. Feel free to reactivate with your reasoning if you disagree. For now, closing because this hasn't been getting traction for so long.
We have no libraries that need licenses.

**Comment by AndroidDeveloperLB** [comment]
Please offer it in a more standard place, like other apps. In "about" menu item.
It's not intuitive at all to find this there.
